
//Greetings: Start with the array you used in Exercise 11, but instead of just printing each person’s name, print a message to them. 
//The text of each message should be the same, but each message should be personalized with the person’s name.



//EX: 12//
console.log("\nEX:12, Greetings:- \n")

var _name = ["Amna,","Ali,","Ayesha,","Naveera,","Areeba,","Arsalan"];
var msg= "Welcome to new session!";

_name.forEach((n) =>{
    console.log(n, msg)
}
);