//Your Own Array: Think of your favorite mode of transportation, such as a motorcycle or a car, and make a list that stores several examples. 
//Use your list to print a series of statements about these items, such as “I would like to own a Honda motorcycle.”



//EX: 13//
console.log("\n EX: 13, Your Own Array:-\n")
let transport=["ferrari","Audi","BMW"]

console.log(" I would like to own a " + transport[0] + " Car.")

console.log(" I would like to own a " + transport[1] + " Car.")

console.log(" I would like to own a " + transport[2] + " Car.")

