//Guest List: If you could invite anyone, living or deceased, to dinner, who would you invite? 
//Make a list that includes at least three people you’d like to invite to dinner. Then use your list to print a message to each person, 
//inviting them to dinner.



//EX: 14///
console.log("\n EX: 14, Guest List:-\n")
var invitedppl = ["Amna","Ali","Ayesha"];
var invitation= "Sending you my heartiest invitation to join this dinner party."

invitedppl.forEach((n) =>{
    console.log( "Hey"+ " "+n+ "!"+" " + invitation)
}
);