
//They think of something you could store in a JavaScript Object. Write a program that creates Objects containing these items.



//EX: 21//  
 console.log("\nEX:21,Think of something you could store in a Object:-\n") 

   
    let Country = { countryname:"PAKISTAN",
                    Full_name: "Islamic Republic of Pakistan",
                    founder: "Quaid-e-Azam",
                    Capital: "Islamabad",
                    Largest_city: "Karachi",
                    Provinces: "4",
                    
    }
    console.log(Country)
