//Intentional Error: If you haven’t received an array index error in one of your programs yet, try to make one happen. Change an index in one of your programs to produce an index error. 
//Make sure you correct the error before closing the program.


//EX: 22// 
console.log("\n EX:22, Intentional Error:-\n")

let languages=["Urdu","Sindhi","Punjabi","Saraiki","Balochi"]
 console.log("error: "+languages[5])
 console.log("correction: "+languages[1])