
//Conditional Tests: Write a series of conditional tests. Print a statement describing each test and your prediction for the results of each test. 
//Your code should look something like this:

//let car = 'subaru';

//console.log("Is car == 'subaru'? I predict True.")

//console.log(car == 'subaru')

//• Look closely at your results, and make sure you understand why each line evaluates to True or False.

//• Create at least 10 tests. Have at least 5 tests evaluate to True and another 5 tests evaluate to False.





//EX: 23//
console.log("\nEX:23, Conditional Tests::-\n")


console.log("\n 5 test to evalute true \n")

var mobile="sumsung"
console.log("TEST:1 Is mobile == 'sumsung'")
if(mobile=="sumsung"){
console.log("True")
}
else{
    console.log("False")
}

var num=14
console.log("TEST:2 Is num == '14'")
if(num==14){
console.log("True")
}
else{
    console.log("False")
}

var game="TIC TAC"
console.log("TEST:3 Is game == 'TIC TAC'")
if(game=="TIC TAC"){
console.log("True")
}
else{
    console.log("False")
}

var language="JAVASCRIPT"
console.log("TEST:4 Is language == 'JAVASCRIPT'")
if(language=="JAVASCRIPT"){
console.log("True")
}
else{
    console.log("False")
}

var num1=15
console.log("TEST:5 Is car >= '10'")
if(num1>=10){
    
        console.log("True")
        }
        else{
            console.log("False")
        
}





console.log("\n5 test to evalute False\n")

var mobile="sumsung"
console.log("TEST:1 Is mobile == 'VIVO'?")
if(mobile == "VIVO"){
console.log("True")
}
else{
    console.log("False")
}

var num=14
console.log("TEST:2 Is num != '14'?")
if(num!=14){
console.log("True")
}
else{
    console.log("False")
}

var game="TIC TAC"
console.log("TEST:3 Is game == 'pubg'?")
if(game=="pubg"){
console.log("True")
}
else{
    console.log("False")
}

var language="JAVASCRIPT"
console.log("TEST:4 Is language == 'TYPESCRIPT'?")
if(language=="TYPESCRIPT"){
con
}
else{
    console.log("False")
}

var num1=15
console.log("TEST:5  Is car != 3*5?")
if(num1!=3*5){
    
        console.log("True")
        }
        else{
            console.log("False")
        
}




