
//Favorite Fruit: Make a array of your favorite fruits, and then write a series of independent if statements that check for certain fruits in your array.
//• Make a array of your three favorite fruits and call it favorite_fruits.

//• Write five if statements. Each should check whether a certain kind of fruit is in your array. 
//If the fruit is in your array, the if block should print a statement, such as You really like bananas!




EX: 29//
console.log("\n EX:29, Favorite Fruit:-\n");

var fvrt_fruits=["Apple","Mango","Orange"];

for(i=0; i<fvrt_fruits.length; i++){

if(fvrt_fruits[0]==="Apple"){
  console.log("I really like Apple");
}

else{
  console.log("Not found");
}
if(fvrt_fruits[1]=="Mango"){
  console.log("I really like mango");
}

else{
  console.log("Not found");
}
if(fvrt_fruits[2]==="Orange"){
  console.log("I really like Orange");
}

else{
  console.log("Not found");
}
if(fvrt_fruits[0]=="Bannana"){
  console.log("I really like Bannana");
}

else{
  console.log("Not found");
}
if(fvrt_fruits[2]==="apple"){
  console.log("I really like Apple");
}

else{
  console.log("Not found")
}
}
