//T-Shirt: Write a function called make_shirt() that accepts a size and the text of a message that should be printed on the shirt.
 //The function should print a sentence summarizing the size of the shirt and the message printed on it. 
//Call the function.


//EX: 36//
console.log("EX:36 T-Shirt:-")

function make_shirt(info){
  console.log(info)

}
make_shirt({
  'size':14,
  'print':"hello to JS"
})