
//Famous Quote: Find a quote from a famous person you admire. Print the quote and the name of its author. Your output should look something like the following, including the quotation marks:

///Albert Einstein once said, “A person who never made a mistake never tried anything new.”

//EX: 4//
console.log("\n EX:4, Famous Quote:- \n")

console.log("Bill Gates once said, \"Success is a lousy Teacher. It seduces smart people into thinking they can not lose\".");

