//Famous Quote 2: Repeat Exercise 4, but this time store the famous person’s name in a variable called famous_person.
 //Then compose your message and store it in a new variable called message. Print your message.





//EX: 5//
console.log("\n EX:5, Famous Quote 2: - \n")

let famous_person="Bill Gates";
let his_qoute="once said, \"Success is a lousy Teacher. It seduces smart people into thinking they can not lose\".";
    
         console.log(famous_person, his_qoute)