
//Stripping Names: Store a person’s name, and include some whitespace characters at the beginning and end of the name. 
//Make sure you use each character combination, "\t" and "\n", at least once. Print the name once, so the whitespace around the name is displayed. 
//Then print the name after striping the white spaces.




 //EX: 6//
console.log("\n EX:6, Stripping Names:- \n")

console.log("printing with whitespace character")

var fullname = "ali \thaider."
console.log(fullname);

var fullname = "ali \nhaider."
console.log(fullname);

console.log("printing without whitespace character")
let _fullname = "ali haider"
console.log(_fullname);

