//You should create four lines that look like this:

//console.log(5 + 3)

///Your output should simply be four lines with the number 8 appearing once on each line.





//EX: 8//
console.log("\n EX:8, create four line:-\n")

 console.log("___________")
 console.log(5+3)
 console.log("___________")
 console.log(5+3)
 console.log("___________")
 console.log(5+3)
 console.log("___________")
 console.log(5+3)
 